//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompetitionApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolExtraTimeStampField
    {
        public int ExtraFielsID { get; set; }
        public int ProtocolID { get; set; }
        public string ExtraFieldName { get; set; }
        public byte[] Content { get; set; }
    
        public virtual Protocols Protocols { get; set; }
    }
}
