//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompetitionApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Expert = new HashSet<Expert>();
            this.ProtocolAndUser = new HashSet<ProtocolAndUser>();
        }

        public string FullName => Surname + " " + Name + " " + LastName;

        public int ID { get; set; }
        public int CompetiotionID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string PIN { get; set; }
        public byte GenderID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public short UserRoleID { get; set; }
        public string SkillID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public short UserStatusID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Competition Competition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expert> Expert { get; set; }
        public virtual Expert Expert1 { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocolAndUser> ProtocolAndUser { get; set; }
        public virtual Region Region { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual UserStatus UserStatus { get; set; }
    }
}
